import { Task, Habit, CircleMember, CircleFeedPost, FocusSession } from '../types';

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Review Q3 Design System Guidelines',
    description: 'Audit the terracotta & dusty rose color contrast ratios across mobile viewports.',
    priority: 'high',
    tags: ['design', 'work'],
    dueDate: 'Today',
    completed: false,
    isTodayFocus: true,
    timeBlock: 'morning',
    estimatedMinutes: 45,
  },
  {
    id: 'task-2',
    title: 'Draft Tactical Product Roadmap',
    description: 'Outline key milestones for social rhythm features and realtime co-working rooms.',
    priority: 'high',
    tags: ['strategy', 'product'],
    dueDate: 'Today',
    completed: false,
    isTodayFocus: true,
    timeBlock: 'morning',
    estimatedMinutes: 60,
  },
  {
    id: 'task-6',
    title: 'Audit API Performance & Latency Metrics',
    description: 'Verify database query execution times and eliminate N+1 latency bottlenecks.',
    priority: 'high',
    tags: ['engineering', 'work'],
    dueDate: 'Today',
    completed: false,
    isTodayFocus: true,
    timeBlock: 'morning',
    estimatedMinutes: 30,
  },
  {
    id: 'task-7',
    title: 'Finalize Sprint Deliverables & PR Review',
    description: 'Review pending pull requests and sync release notes with team leads.',
    priority: 'medium',
    tags: ['engineering', 'planning'],
    dueDate: 'Today',
    completed: false,
    isTodayFocus: true,
    timeBlock: 'morning',
    estimatedMinutes: 25,
  },
  {
    id: 'task-3',
    title: '30-minute Deep Breath & Meditation',
    description: 'Reset mental clarity before evening focus sprint.',
    priority: 'medium',
    tags: ['personal', 'mindset'],
    dueDate: 'Today',
    completed: true,
    completedAt: new Date().toISOString(),
    isTodayFocus: true,
    timeBlock: 'afternoon',
    estimatedMinutes: 30,
  },
  {
    id: 'task-4',
    title: 'Refactor Supabase Realtime Channel Listeners',
    description: 'Ensure clean cleanup on component unmount and error retry strategy.',
    priority: 'medium',
    tags: ['engineering', 'work'],
    dueDate: 'Today',
    completed: false,
    isTodayFocus: true,
    timeBlock: 'afternoon',
    estimatedMinutes: 40,
  },
  {
    id: 'task-8',
    title: 'Evening Journaling & Goal Retrospective',
    description: 'Reflect on today’s output metrics and prepare tomorrow’s top 3 priority focus tasks.',
    priority: 'low',
    tags: ['mindset', 'personal'],
    dueDate: 'Today',
    completed: false,
    isTodayFocus: true,
    timeBlock: 'evening',
    estimatedMinutes: 20,
  },
  {
    id: 'task-5',
    title: 'Weekly Meal Prep & Grocery Run',
    description: 'Stock up on oat milk, fresh berries, and herbal tea.',
    priority: 'low',
    tags: ['personal'],
    dueDate: 'This Weekend',
    completed: false,
    isTodayFocus: false,
    timeBlock: null,
    estimatedMinutes: 90,
  },
];

const today = new Date().toISOString().split('T')[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
const twoDaysAgo = new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0];

export const INITIAL_HABITS: Habit[] = [
  {
    id: 'habit-1',
    title: 'Hydrate 2.5L Water',
    category: 'health',
    icon: '💧',
    streak: 12,
    completedDates: [today, yesterday, twoDaysAgo],
    frequency: 'daily',
    targetDaysPerWeek: 7,
    createdAt: '2026-09-01',
  },
  {
    id: 'habit-2',
    title: 'Read 20 Pages Non-Fiction',
    category: 'mindset',
    icon: '📚',
    streak: 7,
    completedDates: [today, yesterday],
    frequency: 'daily',
    targetDaysPerWeek: 7,
    createdAt: '2026-09-05',
  },
  {
    id: 'habit-3',
    title: 'Morning Sunlight Walk',
    category: 'fitness',
    icon: '🌅',
    streak: 5,
    completedDates: [today, twoDaysAgo],
    frequency: 'daily',
    targetDaysPerWeek: 5,
    createdAt: '2026-09-10',
  },
  {
    id: 'habit-4',
    title: 'Evening Journaling & Reflection',
    category: 'creative',
    icon: '✍️',
    streak: 18,
    completedDates: [yesterday, twoDaysAgo],
    frequency: 'daily',
    targetDaysPerWeek: 7,
    createdAt: '2026-08-20',
  },
];

export const INITIAL_CIRCLE_MEMBERS: CircleMember[] = [
  {
    id: 'user-1',
    name: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'focusing',
    statusText: 'In Pomodoro: UI Polish',
    closedRingsCount: 2,
    streak: 14,
    activeSoundscape: 'Rain on Leaves',
    isCirclePartner: true,
    isMuted: false,
  },
  {
    id: 'user-2',
    name: 'Marcus Vance',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'completed_day',
    statusText: 'Closed 3/3 Rings today! 🎉',
    closedRingsCount: 3,
    streak: 21,
    isCirclePartner: true,
    isMuted: false,
  },
  {
    id: 'user-3',
    name: 'Sora Takahashi',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    status: 'idle',
    statusText: 'Taking a 10m tea break',
    closedRingsCount: 1,
    streak: 8,
    isCirclePartner: true,
    isMuted: false,
  },
  {
    id: 'user-4',
    name: 'Amara Okafor',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    status: 'focusing',
    statusText: 'Deep Work: Backend API',
    closedRingsCount: 2,
    streak: 30,
    activeSoundscape: 'Lo-Fi Autumn Beats',
    isCirclePartner: true,
    isMuted: false,
  },
];

export const INITIAL_CIRCLE_FEED: CircleFeedPost[] = [
  {
    id: 'feed-1',
    userId: 'user-2',
    userName: 'Marcus Vance',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    type: 'ring_closed',
    title: 'Closed All 3 Daily Progress Rings! 🌟',
    detail: 'Finished 5 focus sessions (125 mins), 4 habits, and 6 priority tasks.',
    timestamp: '25 mins ago',
    likes: 12,
    userLiked: true,
  },
  {
    id: 'feed-2',
    userId: 'user-4',
    userName: 'Amara Okafor',
    userAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    type: 'streak_milestone',
    title: '30-Day Focus Streak Milestone! 🔥',
    detail: 'Maintained non-stop daily tactical focus routines for a full month.',
    timestamp: '2 hours ago',
    likes: 19,
    userLiked: false,
  },
  {
    id: 'feed-3',
    userId: 'user-1',
    userName: 'Elena Rostova',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    type: 'focus_marathon',
    title: 'Logged 120 Minutes of Deep Work 🌾',
    detail: 'Completed 4 Pomodoros with Lo-Fi Autumn Beats audio soundscape.',
    timestamp: '4 hours ago',
    likes: 8,
    userLiked: false,
  },
];

export const INITIAL_FOCUS_SESSIONS: FocusSession[] = [
  {
    id: 'f-1',
    durationMinutes: 25,
    taskTitle: 'Review Q3 Design System Guidelines',
    mode: 'pomodoro',
    completedAt: new Date(Date.now() - 7200000).toISOString(),
    soundscape: 'Lo-Fi Autumn Beats',
  },
  {
    id: 'f-2',
    durationMinutes: 25,
    taskTitle: 'Draft Tactical Product Roadmap',
    mode: 'pomodoro',
    completedAt: new Date(Date.now() - 3600000).toISOString(),
    soundscape: 'Gentle Rain',
  },
];
